### ISSUE TITLE
USA Counties shifts randomly

### ISSUE THREAD

**Issue by kkay82** [kkay82/NAPSG-Foundation-Tech-Innovation#19]
Able to replicate the issue by bringing up the attribute table and then closing it.

![image](https://user-images.githubusercontent.com/67169954/102908424-ac061500-4434-11eb-92b6-fdb3c559f586.png)

**Comment by kkay82** [comment]
Also replicated in the add data piece:

![image](https://user-images.githubusercontent.com/67169954/102909930-f4becd80-4436-11eb-9a89-e1409ea5a00f.png)

**Comment by afackler** [comment]
I was not able to replicate this after trying what you mentioned above. Maybe try showing me if you have this happen again

**Comment by kkay82** [comment]
Got it to do it a few different times but seems more sporadic now. Will keep testing.

**Comment by kkay82** [comment]
Closing for now. Kevin/Adam replicated the issue, but counties snap back after changing map extent. Not a huge bug, will keep an eye on it if there are other reports.
