### ISSUE TITLE
NAPSG logo links to a static image

### ISSUE THREAD

**Issue by kkay82** [kkay82/NAPSG-Foundation-Tech-Innovation#21]
The NAPSG logos on the sandbox should link to the NAPSG website. The second logo down links to the AGOL item.

![image](https://user-images.githubusercontent.com/67169954/102910873-7ebb6600-4438-11eb-8692-f2ce2583b5b9.png)

**Comment by kkay82** [comment]
Broken on the edit shelters and public information tabs.

**Comment by afackler** [comment]
Logo is fixed, it now is linked to NAPSG's webpage. I downloaded the logo, then uploaded it, and changed the link to the web page.

**Comment by kkay82** [comment]
All work except the logo on the public info app:

![image](https://user-images.githubusercontent.com/67169954/103826810-cf37e380-5034-11eb-99e7-f29995548837.png)

**Comment by afackler** [comment]
Fixed, it should work fine now.
