### ISSUE TITLE
Directions on public map - multiple options

### ISSUE THREAD

**Issue by kkay82** [kkay82/NAPSG-Foundation-Tech-Innovation#22]
There are two separate directions options in the public map. 

Option 1 is a hack to open google maps. This option exists when you click the shelter on the map or the get directions button under shelter information.

Option 2 is the direction function in the near me widget. I am not sure we need both, if this costs credits, or what?

Thoughts?

![image](https://user-images.githubusercontent.com/67169954/102913336-db6c5000-443b-11eb-9bf8-22fde5153ca7.png)

**Comment by afackler** [comment]
I think the Google Maps link is fine to keep - it would be helpful to the public if they need to use a GPS to navigate to a shelter. I don't think the Directions cost credits

**Comment by kkay82** [comment]
Added Colleen to get her perspective as well, then can close it afterwards.

**Comment by CLivingstone** [comment]
I agree with Adam that a link to Google Maps is fine, and users may prefer to view directions in a familiar navigation app.  Also, I believe generating driving directions in the Near Me widget does cost credits: https://doc.arcgis.com/en/web-appbuilder/create-apps/widget-near-me.htm

**Comment by kkay82** [comment]
Okay, lets confirm if it does or doesn't use credits. Especially in a sandbox, I don't want to be spending credits each time someone tests the direction button.

![image](https://user-images.githubusercontent.com/67169954/103924629-8d11af00-50d3-11eb-99fd-7242da9f6f6a.png)

**Comment by afackler** [comment]
Maybe something to change in the shelter editor is instead of just "Address", label as "Full Address". For example, on a point I dropped I put the address as 300 Church St and it took me to DC, not my point in Illinois. As for the routing, I think we can take that out if that is doable. No point to spend credits if it already links to Google.

**Comment by kkay82** [comment]
Good call. I wish the tool allowed for auto completing address, where when you start typing if gives you the full address with city/zip. Lets go ahead and change the shelter editor to say full address.

Looks like you removed the routing already, I agree. The google direction button works great.

**Comment by afackler** [comment]
Okay, figured out how to change the alias to Full Address and just took care of that
